# Generated by Django 4.1.2 on 2022-10-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='picture1')),
                ('desc', models.TextField()),
                ('price', models.ImageField(upload_to='')),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
