# Generated by Django 4.1.2 on 2022-10-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sajnatravelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='picture2')),
                ('date', models.DateField()),
                ('name1', models.CharField(max_length=200)),
                ('desc1', models.TextField()),
            ],
        ),
    ]
